import { Menu, Search, ShoppingBag } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type LandingHeaderProps = { storeLogo?: string; storeName?: string; itemCount: number; searchQuery: string; onSearchChange: (value: string) => void; onOpenMenu: () => void; onOpenCart: () => void };

export function LandingHeader({ storeLogo, storeName, itemCount, searchQuery, onSearchChange, onOpenMenu, onOpenCart }: LandingHeaderProps) {
  return <header className="sticky top-0 z-20 bg-white shadow-sm"><div className="bg-[#c4002c] px-4 py-2 text-center text-[11px] font-bold tracking-wide text-white sm:text-xs">Freshly prepared favourites — order online for delivery or collection.</div><div className="mx-auto grid max-w-7xl grid-cols-[auto_1fr_auto] items-center gap-3 px-4 py-4 sm:px-6"><Button type="button" variant="ghost" size="icon" className="rounded-full text-[#7c001c] hover:bg-rose-50" onClick={onOpenMenu} aria-label="Open menu"><Menu className="h-5 w-5" /></Button><div className="justify-self-center text-center"><img className="mx-auto h-12 w-12 rounded-full object-cover sm:h-14 sm:w-14" src={storeLogo || "/logo.png"} alt={storeName || "Urban Spice"} /><p className="mt-1 text-sm font-black uppercase tracking-[0.16em] text-[#7c001c]">{storeName || "Urban Spice"}</p></div><Button type="button" variant="ghost" size="icon" onClick={onOpenCart} className="relative rounded-full text-[#7c001c] hover:bg-rose-50" aria-label="Open cart"><ShoppingBag className="h-5 w-5" />{itemCount > 0 && <span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-[#c4002c] px-1 text-[10px] font-black text-white">{itemCount}</span>}</Button></div><div className="border-t border-stone-100 px-4 py-3"><div className="relative mx-auto max-w-xl"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-stone-400" /><Input value={searchQuery} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search Urban Spice" className="h-10 rounded-full border-stone-200 bg-stone-50 pl-10 text-[#3d0a16] placeholder:text-stone-400 focus-visible:border-[#c4002c] focus-visible:ring-[#c4002c]/20" /></div></div></header>;
}
