import { Plus, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Product } from "./types";

const formatMoney = (value: number) => `Rs. ${Math.round(value).toLocaleString()}`;
type ProductGridProps = { products: Product[]; onAdd: (product: Product) => void; onCustomize: (product: Product) => void };

export function ProductGrid({ products, onAdd, onCustomize }: ProductGridProps) {
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{products.map((product) => <article key={product.id} className="group relative min-h-[176px] overflow-hidden rounded-[1.75rem] bg-[#32170e] shadow-lg shadow-orange-950/10"><img src={product.image || "/logo.png"} alt="" className="absolute inset-0 h-full w-full object-cover opacity-75 transition duration-500 group-hover:scale-105 group-hover:opacity-90" /><div className="absolute inset-0 bg-gradient-to-r from-[#32170e] via-[#32170e]/75 to-transparent" /><div className="relative flex min-h-[176px] flex-col justify-between p-5"><div className="max-w-[72%]"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-orange-300">{product.category?.name || "Urban Spice"}</p><h2 className="mt-2 text-xl font-black leading-tight tracking-tight text-white">{product.name}</h2><p className="mt-2 line-clamp-2 text-xs leading-5 text-orange-100/75">{product.description || "Freshly prepared with bold Urban Spice flavour."}</p></div><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-orange-200/70">{product.isPizza ? "Starting at" : "Price"}</p><strong className="text-lg font-black text-orange-300">{formatMoney(product.basePrice)}</strong></div><Button type="button" size="icon" className="h-11 w-11 rounded-full bg-orange-400 text-[#32170e] shadow-lg shadow-black/20 hover:scale-105 hover:bg-orange-300" onClick={() => product.isPizza ? onCustomize(product) : onAdd(product)} aria-label={product.isPizza ? `Customize ${product.name}` : `Add ${product.name} to order`}>{product.isPizza ? <SlidersHorizontal className="h-4 w-4" /> : <Plus className="h-5 w-5" />}</Button></div></div></article>)}</div>;
}
