import { Plus, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Product } from "./types";

const formatMoney = (value: number) => `Rs. ${Math.round(value).toLocaleString()}`;
type ProductGridProps = { products: Product[]; onAdd: (product: Product) => void; onCustomize: (product: Product) => void };

export function ProductGrid({ products, onAdd, onCustomize }: ProductGridProps) {
  return <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{products.map((product) => <article key={product.id} className="group overflow-hidden rounded-[1.5rem] border border-stone-200 bg-white shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-stone-900/10"><div className="relative aspect-[4/3] overflow-hidden bg-stone-100"><img src={product.image || "/logo.png"} alt={product.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" />{product.isPizza && <span className="absolute left-3 top-3 rounded-full bg-white px-3 py-1 text-[10px] font-black uppercase tracking-wider text-[#32170e] shadow-md">Customize</span>}</div><div className="p-4"><p className="text-[10px] font-black uppercase tracking-[0.16em] text-orange-600">{product.category?.name || "Urban Spice"}</p><h2 className="mt-1.5 truncate text-base font-black tracking-tight text-[#32170e]">{product.name}</h2><p className="mt-2 line-clamp-2 min-h-10 text-xs leading-5 text-stone-500">{product.description || "Freshly prepared Urban Spice favourite."}</p><div className="mt-4 flex items-center justify-between gap-3 border-t border-stone-100 pt-3"><strong className="text-base text-[#32170e]">{product.isPizza ? "From " : ""}{formatMoney(product.basePrice)}</strong><Button type="button" size="icon" className="h-9 w-9 rounded-full bg-orange-500 text-[#32170e] shadow-sm hover:bg-orange-400" onClick={() => product.isPizza ? onCustomize(product) : onAdd(product)} aria-label={product.isPizza ? `Customize ${product.name}` : `Add ${product.name} to order`}>{product.isPizza ? <SlidersHorizontal className="h-4 w-4" /> : <Plus className="h-5 w-5" />}</Button></div></div></article>)}</div>;
}
